AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Test Application
Resources:
  MyTestDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties :
      TableName: MyTestDynamoDBTable
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /helloWorld
            Method: GET
  RandomFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: random.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /randomNumber
            Method: GET
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /test
            Method: GET