AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Test Application
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /helloWorld
            Method: GET
  RandomFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: random.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /randomNumber
            Method: GET