AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Test Application
Resources:
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowLambdaServiceToAssumeRole"
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Role: !GetAtt IamRoleLambdaExecution.Arn
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /helloWorld
            Method: GET
  RandomFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: random.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Role: !GetAtt IamRoleLambdaExecution.Arn
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /randomNumber
            Method: GET
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: test.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Role: !GetAtt IamRoleLambdaExecution.Arn
      Events:
        MyTestAPI:
          Type: Api
          Properties:
            Path: /test
            Method: GET
  MyTestDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties :
      TableName: MyTestDynamoDBTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  MyTestDynamoDBTableIamPolicy:
    Type: AWS::IAM::Policy
    DependsOn: MyTestDynamoDBTable
    Properties:
      PolicyName: MyTestDynamoDBTableIamPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
            Resource: arn:aws:dynamodb:*:*:table/MyTestDynamoDBTable
      Roles:
        - Ref: IamRoleLambdaExecution